package services

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/huangang/codesentry/backend/internal/config"
	"github.com/huangang/codesentry/backend/internal/models"
	"github.com/huangang/codesentry/backend/pkg/logger"
	"gorm.io/gorm"
)

// AutoFixService handles AI-powered code fix generation and PR/MR creation.
type AutoFixService struct {
	db         *gorm.DB
	aiService  *AIService
	httpClient *http.Client
}

func NewAutoFixService(db *gorm.DB, aiCfg *config.OpenAIConfig) *AutoFixService {
	return &AutoFixService{
		db:         db,
		aiService:  NewAIService(db, aiCfg),
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

// FilePatch represents a single file change generated by AI.
type FilePatch struct {
	FilePath string `json:"file_path"`
	Content  string `json:"content"` // New file content
	Action   string `json:"action"`  // "update" or "create"
}

// FixResult represents the result of an auto-fix attempt.
type FixResult struct {
	PRURL   string
	PRTitle string
}

const autoFixPrompt = `You are a code fix assistant. Given the following code review feedback and the original diff, generate code fixes.

## Review Feedback
%s

## Original Diff
%s

## Instructions
Generate fixes for the issues identified in the review. Return ONLY a valid JSON array of file patches.
Each patch should have:
- "file_path": the relative file path
- "content": the COMPLETE fixed content for that file (not just the changes)
- "action": "update"

Example format:
[{"file_path":"src/main.go","content":"package main\n...","action":"update"}]

IMPORTANT: Return ONLY the JSON array, no markdown fencing, no explanations.`

// RequestFix generates AI-powered code fixes and creates a PR/MR.
func (s *AutoFixService) RequestFix(ctx context.Context, reviewLogID uint) (*FixResult, error) {
	var reviewLog models.ReviewLog
	if err := s.db.First(&reviewLog, reviewLogID).Error; err != nil {
		return nil, fmt.Errorf("review log not found: %w", err)
	}

	if reviewLog.ReviewStatus != "completed" {
		return nil, fmt.Errorf("review must be completed before requesting fix")
	}

	var project models.Project
	if err := s.db.First(&project, reviewLog.ProjectID).Error; err != nil {
		return nil, fmt.Errorf("project not found: %w", err)
	}

	// Mark as pending
	reviewLog.FixStatus = "pending"
	s.db.Save(&reviewLog)

	// Build the fix prompt
	prompt := fmt.Sprintf(autoFixPrompt, reviewLog.ReviewResult, reviewLog.DiffContent)

	// If DiffContent is empty, try to fetch it
	if reviewLog.DiffContent == "" {
		prompt = fmt.Sprintf(autoFixPrompt, reviewLog.ReviewResult, "(diff not available - generate fixes based on the review feedback above)")
	}

	// Call AI to generate fixes
	response, _, err := s.aiService.CallWithConfig(ctx, 0, prompt)
	if err != nil {
		reviewLog.FixStatus = "failed"
		s.db.Save(&reviewLog)
		return nil, fmt.Errorf("AI fix generation failed: %w", err)
	}

	// Parse the AI response into file patches
	patches, err := s.parsePatches(response)
	if err != nil {
		reviewLog.FixStatus = "failed"
		s.db.Save(&reviewLog)
		return nil, fmt.Errorf("failed to parse AI fix: %w", err)
	}

	if len(patches) == 0 {
		reviewLog.FixStatus = "failed"
		s.db.Save(&reviewLog)
		return nil, fmt.Errorf("AI did not generate any fixes")
	}

	// Create branch, commit, and PR/MR
	branchName := fmt.Sprintf("codesentry/fix-%d-%s", reviewLog.ID, reviewLog.CommitHash[:8])
	prTitle := fmt.Sprintf("[CodeSentry Auto-Fix] Fix issues in %s", reviewLog.CommitHash[:8])

	var result *FixResult
	switch project.Platform {
	case "github":
		result, err = s.createGitHubFixPR(&project, &reviewLog, patches, branchName, prTitle)
	case "gitlab":
		result, err = s.createGitLabFixMR(&project, &reviewLog, patches, branchName, prTitle)
	default:
		err = fmt.Errorf("auto-fix not supported for platform: %s", project.Platform)
	}

	if err != nil {
		reviewLog.FixStatus = "failed"
		s.db.Save(&reviewLog)
		return nil, err
	}

	// Update review log with fix PR URL
	reviewLog.FixStatus = "completed"
	reviewLog.FixPRURL = result.PRURL
	s.db.Save(&reviewLog)

	logger.Infof("[AutoFix] Created fix PR for review %d: %s", reviewLogID, result.PRURL)
	return result, nil
}

// GetFixStatus returns the fix status of a review log.
func (s *AutoFixService) GetFixStatus(reviewLogID uint) (string, string, error) {
	var reviewLog models.ReviewLog
	if err := s.db.First(&reviewLog, reviewLogID).Error; err != nil {
		return "", "", fmt.Errorf("review log not found: %w", err)
	}
	return reviewLog.FixStatus, reviewLog.FixPRURL, nil
}

func (s *AutoFixService) parsePatches(response string) ([]FilePatch, error) {
	// Clean response: strip markdown code fences if present
	cleaned := strings.TrimSpace(response)
	if strings.HasPrefix(cleaned, "```") {
		lines := strings.Split(cleaned, "\n")
		if len(lines) > 2 {
			cleaned = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}

	var patches []FilePatch
	if err := json.Unmarshal([]byte(cleaned), &patches); err != nil {
		return nil, fmt.Errorf("invalid JSON from AI: %w", err)
	}
	return patches, nil
}

// --- GitHub Fix PR Creation ---

func (s *AutoFixService) createGitHubFixPR(project *models.Project, reviewLog *models.ReviewLog, patches []FilePatch, branchName, prTitle string) (*FixResult, error) {
	owner, repo := s.parseGitHubRepo(project.URL)
	if owner == "" || repo == "" {
		return nil, fmt.Errorf("failed to parse GitHub repo from URL: %s", project.URL)
	}

	baseURL := "https://api.github.com"

	// 1. Get the base commit SHA (the commit being reviewed)
	baseSHA := reviewLog.CommitHash

	// 2. Create a new branch from the base commit
	refPayload := map[string]string{
		"ref": "refs/heads/" + branchName,
		"sha": baseSHA,
	}
	if err := s.githubPost(baseURL+"/repos/"+owner+"/"+repo+"/git/refs", project.AccessToken, refPayload, nil); err != nil {
		return nil, fmt.Errorf("failed to create branch: %w", err)
	}

	// 3. Commit each file patch to the branch
	for _, patch := range patches {
		filePayload := map[string]interface{}{
			"message": fmt.Sprintf("[CodeSentry] Fix %s", patch.FilePath),
			"content": encodeBase64(patch.Content),
			"branch":  branchName,
		}

		// Get current file SHA if updating
		fileSHA := s.getGitHubFileSHA(baseURL, owner, repo, patch.FilePath, branchName, project.AccessToken)
		if fileSHA != "" {
			filePayload["sha"] = fileSHA
		}

		apiURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s", baseURL, owner, repo, patch.FilePath)
		if err := s.githubPut(apiURL, project.AccessToken, filePayload, nil); err != nil {
			return nil, fmt.Errorf("failed to update file %s: %w", patch.FilePath, err)
		}
	}

	// 4. Create PR
	targetBranch := reviewLog.Branch
	if targetBranch == "" {
		targetBranch = "main"
	}
	prPayload := map[string]interface{}{
		"title": prTitle,
		"head":  branchName,
		"base":  targetBranch,
		"body":  fmt.Sprintf("Auto-generated fix by CodeSentry AI for review #%d.\n\nOriginal review score: %.0f/100\n\n---\n*This PR was automatically generated by [CodeSentry](https://github.com/huangang/codesentry)*", reviewLog.ID, safeScore(reviewLog.Score)),
	}

	var prResp struct {
		HTMLURL string `json:"html_url"`
	}
	if err := s.githubPost(baseURL+"/repos/"+owner+"/"+repo+"/pulls", project.AccessToken, prPayload, &prResp); err != nil {
		return nil, fmt.Errorf("failed to create PR: %w", err)
	}

	return &FixResult{PRURL: prResp.HTMLURL, PRTitle: prTitle}, nil
}

func (s *AutoFixService) parseGitHubRepo(projectURL string) (string, string) {
	u := strings.TrimSuffix(projectURL, ".git")
	parts := strings.Split(u, "/")
	if len(parts) < 2 {
		return "", ""
	}
	return parts[len(parts)-2], parts[len(parts)-1]
}

func (s *AutoFixService) getGitHubFileSHA(baseURL, owner, repo, filePath, branch, token string) string {
	apiURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s?ref=%s", baseURL, owner, repo, filePath, branch)
	req, _ := http.NewRequest("GET", apiURL, nil)
	req.Header.Set("Authorization", "token "+token)
	resp, err := s.httpClient.Do(req)
	if err != nil || resp.StatusCode != 200 {
		return ""
	}
	defer resp.Body.Close()
	var result struct {
		SHA string `json:"sha"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	return result.SHA
}

func (s *AutoFixService) githubPost(apiURL, token string, payload interface{}, result interface{}) error {
	body, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", apiURL, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "token "+token)
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("github API error (status %d): %s", resp.StatusCode, string(respBody))
	}
	if result != nil {
		json.NewDecoder(resp.Body).Decode(result)
	}
	return nil
}

func (s *AutoFixService) githubPut(apiURL, token string, payload interface{}, result interface{}) error {
	body, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", apiURL, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "token "+token)
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("github API error (status %d): %s", resp.StatusCode, string(respBody))
	}
	if result != nil {
		json.NewDecoder(resp.Body).Decode(result)
	}
	return nil
}

// --- GitLab Fix MR Creation ---

func (s *AutoFixService) createGitLabFixMR(project *models.Project, reviewLog *models.ReviewLog, patches []FilePatch, branchName, mrTitle string) (*FixResult, error) {
	projectPath := s.parseGitLabProject(project.URL)
	if projectPath == "" {
		return nil, fmt.Errorf("failed to parse GitLab project from URL: %s", project.URL)
	}

	baseURL := s.getGitLabBaseURL(project.URL)
	encodedPath := url.PathEscape(projectPath)

	// 1. Create branch
	branchPayload := map[string]string{
		"branch": branchName,
		"ref":    reviewLog.CommitHash,
	}
	if err := s.gitlabPost(fmt.Sprintf("%s/api/v4/projects/%s/repository/branches", baseURL, encodedPath), project.AccessToken, branchPayload, nil); err != nil {
		return nil, fmt.Errorf("failed to create branch: %w", err)
	}

	// 2. Commit files using the commits API
	var actions []map[string]string
	for _, patch := range patches {
		actions = append(actions, map[string]string{
			"action":    "update",
			"file_path": patch.FilePath,
			"content":   patch.Content,
		})
	}

	commitPayload := map[string]interface{}{
		"branch":         branchName,
		"commit_message": fmt.Sprintf("[CodeSentry] Auto-fix for review #%d", reviewLog.ID),
		"actions":        actions,
	}
	if err := s.gitlabPost(fmt.Sprintf("%s/api/v4/projects/%s/repository/commits", baseURL, encodedPath), project.AccessToken, commitPayload, nil); err != nil {
		return nil, fmt.Errorf("failed to commit fixes: %w", err)
	}

	// 3. Create MR
	targetBranch := reviewLog.Branch
	if targetBranch == "" {
		targetBranch = "main"
	}
	mrPayload := map[string]interface{}{
		"source_branch": branchName,
		"target_branch": targetBranch,
		"title":         mrTitle,
		"description":   fmt.Sprintf("Auto-generated fix by CodeSentry AI for review #%d.\n\nOriginal review score: %.0f/100\n\n---\n*This MR was automatically generated by [CodeSentry](https://github.com/huangang/codesentry)*", reviewLog.ID, safeScore(reviewLog.Score)),
	}

	var mrResp struct {
		WebURL string `json:"web_url"`
	}
	if err := s.gitlabPost(fmt.Sprintf("%s/api/v4/projects/%s/merge_requests", baseURL, encodedPath), project.AccessToken, mrPayload, &mrResp); err != nil {
		return nil, fmt.Errorf("failed to create MR: %w", err)
	}

	return &FixResult{PRURL: mrResp.WebURL, PRTitle: mrTitle}, nil
}

func (s *AutoFixService) parseGitLabProject(projectURL string) string {
	u := strings.TrimSuffix(projectURL, ".git")
	protocolIdx := strings.Index(u, "://")
	if protocolIdx == -1 {
		return ""
	}
	rest := u[protocolIdx+3:]
	slashIdx := strings.Index(rest, "/")
	if slashIdx == -1 {
		return ""
	}
	return rest[slashIdx+1:]
}

func (s *AutoFixService) getGitLabBaseURL(projectURL string) string {
	u := strings.TrimSuffix(projectURL, ".git")
	protocolIdx := strings.Index(u, "://")
	if protocolIdx == -1 {
		return "https://gitlab.com"
	}
	rest := u[protocolIdx+3:]
	slashIdx := strings.Index(rest, "/")
	if slashIdx == -1 {
		return u
	}
	return u[:protocolIdx+3+slashIdx]
}

func (s *AutoFixService) gitlabPost(apiURL, token string, payload interface{}, result interface{}) error {
	body, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", apiURL, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("PRIVATE-TOKEN", token)
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("gitlab API error (status %d): %s", resp.StatusCode, string(respBody))
	}
	if result != nil {
		json.NewDecoder(resp.Body).Decode(result)
	}
	return nil
}

// --- Helpers ---

func encodeBase64(s string) string {
	return base64.StdEncoding.EncodeToString([]byte(s))
}

func safeScore(score *float64) float64 {
	if score == nil {
		return 0
	}
	return *score
}
